services:
  # TODO: JUST AN EXAMPLE OF A SERVICE
  web:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

